---

- include: proxy.yml
  with_items:
    - "{'proxy_type': 'private', 'target_server_type': 'private'}"
    - "{'proxy_type': 'public', 'target_server_type': 'public'}"
  vars:
    - config: "{{ proxy_server }}"


