---
- hosts: all
  roles:
    - vpc
  vars_files:
    - "group_vars/secure_vars.yml"
    - "group_vars/vars.yml"
    - "group_vars/cidr_blocks.yml"
  tags:
    - create-vpc

- hosts: all
  roles:
    - fetch-facts
    - ec2-instance
  vars_files:
    - "group_vars/secure_vars.yml"
    - "group_vars/vars.yml"
    - "group_vars/cidr_blocks.yml"
    - "configs/bastion.yml"
    - "configs/build-server.yml"
    - "configs/proxy-server.yml"
    - "configs/dev-hie-instance.yml"
    - "configs/instances.yml"
  tags:
    - create-instance

- hosts: all
  roles:
    - ssh-key
  vars_files:
    - "group_vars/secure_vars.yml"
    - "group_vars/vars.yml"
    - "group_vars/cidr_blocks.yml"
  tags:
    - ssh-key

- hosts: all
  roles:
    - ssl-certs
    - haproxy
  vars_files:
    - "group_vars/secure_vars.yml"
    - "group_vars/vars.yml"
    - "group_vars/cidr_blocks.yml"
    - "configs/bastion.yml"
    - "configs/build-server.yml"
    - "configs/proxy-server.yml"
    - "configs/instances.yml"
  tags:
    - proxy