# Proxy instance spin up must be preceeded the HIE instances.
ec2_instances:
  - { hostname: bastion, spec: "{{ bastion_spec }}" }
  - { hostname: public_proxy, spec: "{{ public_proxy_spec }}" }
  - { hostname: build-ci, spec: "{{ build_server_spec }}" }
  - { hostname: build-agent, spec: "{{ build_server_spec }}" }

