- name:               Create Bastion Security Group
  ec2_group:
    name:             "bastion"
    description:      "Permissions for the bastion box"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:            "{{ bastion_rules }}"
    rules_egress:     "{{ bastion_rules_egress }}"

- name:               Create buildserver Security Group
  ec2_group:
    name:             "buildserver"
    description:      "Permissions for buildserver"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:            "{{ buildserver_rules }}"
    rules_egress:     "{{ buildserver_rules_egress }}"

- name:               Create public proxy Security Group
  ec2_group:
    name:             "public_proxy"
    description:      "Permissions for the http proxies available for public"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:            "{{ public_proxy_rules }}"
    rules_egress:     "{{ public_proxy_rules_egress }}"

- name:               Create SHR Security Group
  ec2_group:
    name:             "shr"
    description:      "Permissions for a machine that runs shr software"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:            "{{ shr_rules }}"
    rules_egress:     "{{ shr_rules_egress }}"